// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqxaoxskhqvhsyzmtnlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxeGFveHNraHF2aHN5em10bmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTk3OTIsImV4cCI6MjA2MTA3NTc5Mn0.lkXjD-mpMRuJd9ebOJMFZsZGvXgr_IYZdJrZHFQv3Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);